apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:       # ✅ secret name
      containers:
        - name: devops-container
          image: kartheek0976/priya:appimage
          ports:
            - containerPort: 8080
      imagePullSecrets:          # ✅ correct place
        - name: dockerhub 

---

apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 8080
      targetPort: 8080

      
