version: "3.9"

services:

  app:
    build: ./Docker-app
    container_name: app1
    ports:
      - "8081:8080"
    environment:
      DB_HOST: devopsdb
      DB_PORT: 3306
      DB_NAME: accounts
      DB_USER: vproapp
      DB_PASSWORD: vproapp
    depends_on:
      - devopsdb
    networks:
      - backend

  devopsdb:
    build: ./Docker-db
    container_name: devopsdb
    environment:
      MYSQL_ROOT_PASSWORD: devopspassword
      MYSQL_DATABASE: accounts
      MYSQL_USER: vproapp
      MYSQL_PASSWORD: vproapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
